[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.10.0",
    "ninja",
    "cmake>=3.12"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/tests/test.py"
test-skip = "*universal2:arm64"
