name: C/C++ CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt install cmake g++-12 libopencv-core-dev
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-12 ..
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
