name: C/C++ CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:22.04

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: apt update && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake make g++-12 libopencv-dev
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-12 ..
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
