name: C/C++ CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    
    # container:
    #  image: ubuntu:22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install dependencies
      run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends cmake make g++-12 libopencv-dev libeigen3-dev
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-12 ..
    - name: Make
      run: cd build && make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
